services:
  api:
    build:
      context: .
      dockerfile: src/AlbertoSouza.BackendChallengeApplication.Api/Dockerfile
    ports:
      - 80:80
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/AlbertoSouza.BackendChallengeApplication.Api:/app