name: Test Workflow

on: 
  push:
    branches:
      - master  # ou a branch que você está usando

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, World!"

      - name: Hello World
        run: echo "Hello, ${{ vars.AWS_BRANCH_PROD }}!"