name: Test Workflow

on: 
  push:
    branches:
      - master  # ou a branch que você está usando

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, World!"

      - name: Hello World
        run: echo "Hello, ${{ vars.AWS_BRANCH_PROD }}!"

      - name: Debug AWS Environment Variables
        run: |
            echo "AWS_REGION: $AWS_REGION"
            echo "AWS_USER_ID: $AWS_USER_ID"
            echo "AWS_REGION: $AWS_REGION.teste"
            echo "AWS_USER_ID: $AWS_USER_ID.teste"
        env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_USER_ID: ${{ secrets.AWS_USER_ID }}